server:
  port: 50
 
spring:
  application:
    name: channel-service-test-ribbon
  cloud:   
    config:
      uri:  http://localhost:8888/  #遠端配置GIT倉庫地址
      profile: prod-50

#Hystrix 設定
feign:
  hystrix:
    enabled: true      

  
#eureka 設定    
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7003/eureka
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka #集群

    register-with-eureka: true # 由於它是一個服務提供者,註冊到eureka
  instance:
    instance-id: channel-servic-test-ribbon-50 # 當前服務例項名稱
    prefer-ip-address: true # 是否使用IP地址作為當前服務的標識,有些是會使用主機號,你可以嘗試註釋看看效果
    # 由於拉取服務和是否把自己註冊到eureka的都是預設true的,所以不需要配置      
